["https://github.com/bevicted/accesspoint"]
# url = "https://github.com/bevicted/accesspoint"
# host = "github.com"
# owner = "bevicted"
# repo = "accesspoint"
alias = "ap"
commits = "{URL}/commits"
commit = "https://github.com/bevicted/accesspoint/commit/{STRING}"
lang = "rust"
