[accesspoint]
url = "https://github.com/bevicted/accesspoint"
test = "{host}/{owner}/{repo}"
host = "github.com"
owner = "bevicted"
repo = "accesspoint"
alias = "ap"
commits = "{url}/commits"
commit = "https://github.com/bevicted/accesspoint/commit/{STRING}"
lang = "rust"
