[accesspoint]
STRING = "ay"
url = "https://github.com/bevicted/accesspoint"
host = "github.com"
owner = "bevicted"
repo = "accesspoint"
alias = "ap"
commits = "{url}/commits"
commit = "https://github.com/bevicted/accesspoint/commit/{STRING}"
lang = "rust"
